# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run: # run tests
          name: test
          command: test

test:
  override:    
  - mocha